import { globSync } from 'node:fs';
import { accentFormat } from './formats/accent.mjs';
import { swiftFormat } from './formats/swift.mjs';
import { tsFormat } from './formats/ts.mjs';

const tokensDir = process.env.OPENBUNNY_TOKENS ?? 'tokens';
const outDir = process.env.OPENBUNNY_OUT ?? '.';
const accentToken = 'color.sprout';

const sources = globSync(`${tokensDir}/*.json`);
if (sources.length === 0) {
  throw new Error(`no token files match ${tokensDir}/*.json`);
}

const cssName = (token) =>
  (['color', 'extension'].includes(token.path[0])
    ? token.path.slice(1)
    : token.path
  ).join('-');

const header = (what) =>
  `/* Generated by Style Dictionary from the tokens directory: ${what}. Do not edit. */\n`;

const requireTokens = (dictionary, destination) => {
  if (dictionary.allTokens.length === 0) {
    throw new Error(`${destination}: the token set is empty`);
  }
};

const referenceName = (token) => {
  const ref = /^\{(.+)\}$/.exec(token.original.$value);
  return ref === null ? undefined : cssName({ path: ref[1].split('.') });
};

const declaration = (token, prefix = '') => {
  const ref = referenceName(token);
  return `  --${prefix}${cssName(token)}: ${ref === undefined ? token.$value : `var(--${ref})`};`;
};

const select = (dictionary, destination, keep) => {
  requireTokens(dictionary, destination);
  const tokens = dictionary.allTokens.filter(keep);
  if (tokens.length === 0)
    throw new Error(`${destination}: no tokens selected`);
  return tokens;
};

const cssRoot = ({ dictionary, file }) => {
  const tokens = select(
    dictionary,
    file.destination,
    (t) => !['native', 'extension', 'color-scheme'].includes(t.path[0]),
  );
  const scheme = dictionary.allTokens.find((t) => t.path[0] === 'color-scheme');
  if (scheme === undefined) {
    throw new Error(`${file.destination}: token color-scheme is missing`);
  }
  const lines = tokens.map((t) => declaration(t)).join('\n');
  return `${header('custom properties')}:root {\n  color-scheme: ${scheme.$value};\n\n${lines}\n}\n`;
};

const cssAliases = ({ dictionary, file }) => {
  const tokens = select(
    dictionary,
    file.destination,
    (t) => t.path[0] === 'extension',
  );
  const lines = tokens.map((t) => declaration(t)).join('\n');
  return `${header('extension aliases')}:root {\n${lines}\n}\n`;
};

const tailwind = ({ dictionary, file }) => {
  const tokens = select(dictionary, file.destination, (t) =>
    ['color', 'font', 'radius'].includes(t.path[0]),
  );
  const lines = tokens.map((t) =>
    t.path[0] === 'color'
      ? `  --color-${cssName(t)}: var(--${cssName(t)});`
      : declaration(t),
  );
  return `${header('Tailwind theme')}@theme inline {\n${lines.join('\n')}\n}\n`;
};

const family = {
  name: 'openbunny/font-family',
  type: 'value',
  filter: (token) =>
    token.$type === 'fontFamily' && Array.isArray(token.$value),
  transform: (token) =>
    token.$value.map((n) => (/\s/.test(n) ? `"${n}"` : n)).join(', '),
};

const name = { name: 'openbunny/name', type: 'name', transform: cssName };

export default {
  usesDtcg: true,
  source: sources,
  log: { warnings: 'error', verbosity: 'default' },
  hooks: {
    transforms: { 'openbunny/font-family': family, 'openbunny/name': name },
    formats: {
      'openbunny/css-root': cssRoot,
      'openbunny/css-aliases': cssAliases,
      'openbunny/css-tailwind': tailwind,
      'openbunny/ts': tsFormat,
      'openbunny/swift': swiftFormat,
      'openbunny/accent': accentFormat(accentToken),
    },
  },
  platforms: {
    css: {
      transforms: ['openbunny/name', 'openbunny/font-family'],
      buildPath: `${outDir}/packages/web/css/`,
      files: [
        { destination: 'tokens.css', format: 'openbunny/css-root' },
        {
          destination: 'extension-aliases.css',
          format: 'openbunny/css-aliases',
        },
        { destination: 'tailwind.css', format: 'openbunny/css-tailwind' },
      ],
    },
    ts: {
      transforms: ['openbunny/name', 'openbunny/font-family'],
      buildPath: `${outDir}/packages/web/src/`,
      files: [{ destination: 'tokens.ts', format: 'openbunny/ts' }],
    },
    swift: {
      transforms: ['openbunny/name'],
      buildPath: `${outDir}/Sources/OpenBunnyTheme/Generated/`,
      files: [{ destination: 'Tokens.swift', format: 'openbunny/swift' }],
    },
    accent: {
      transforms: ['openbunny/name'],
      buildPath: `${outDir}/xcode/AccentColor.colorset/`,
      files: [{ destination: 'Contents.json', format: 'openbunny/accent' }],
    },
  },
};
