const camel = (parts) =>
  parts
    .join('-')
    .replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
    .replace(/^(\d)/, 'n$1');

const weights = {
  100: 'ultraLight',
  200: 'thin',
  300: 'light',
  400: 'regular',
  500: 'medium',
  600: 'semibold',
  700: 'bold',
  800: 'heavy',
  900: 'black',
};

const schemes = new Set(['light', 'dark']);

const channels = (hex, token) => {
  if (!/^#[0-9a-f]{6}$/.test(hex)) {
    throw new Error(`${token}: ${hex} is not a six-digit lowercase hex color`);
  }
  return [1, 3, 5].map((at) => parseInt(hex.slice(at, at + 2), 16));
};

const points = (token) => {
  const match = /^(-?\d+(?:\.\d+)?)px$/.exec(String(token.$value));
  if (match === null) {
    throw new Error(
      `${token.path.join('.')}: ${token.$value} is not a px value`,
    );
  }
  return match[1];
};

const need = (tokens, path) => {
  const token = tokens.find((t) => t.path.join('.') === path);
  if (token === undefined) throw new Error(`token ${path} is missing`);
  return token;
};

const block = (type, lines) =>
  lines.length === 0
    ? ''
    : `\npublic enum ${type} {\n${lines.map((l) => `    ${l}`).join('\n')}\n}\n`;

export const swiftFormat = ({ dictionary, file }) => {
  const tokens = dictionary.allTokens;
  if (tokens.length === 0) {
    throw new Error(`${file.destination}: the token set is empty`);
  }
  const under = (root) => tokens.filter((t) => t.path[0] === root);

  const colors = under('color');
  if (colors.length === 0) {
    throw new Error(`${file.destination}: no color tokens`);
  }
  const colorLines = colors.map((t) => {
    const [r, g, b] = channels(t.$value, t.path.join('.'));
    return `    public static let ${camel(t.path.slice(1))} = Color(\n        .sRGB, red: ${r}.0 / 255.0, green: ${g}.0 / 255.0, blue: ${b}.0 / 255.0)`;
  });
  const palette = colors
    .map(
      (t) =>
        `        "${t.path.slice(1).join('-')}": .${camel(t.path.slice(1))},`,
    )
    .join('\n');

  const families = under('font').map((t) => {
    const first = Array.isArray(t.$value) ? t.$value[0] : t.$value;
    return `public static let ${camel(t.path.slice(1))} = "${first}"`;
  });
  const fontWeights = under('font-weight').map((t) => {
    const weight = weights[t.$value];
    if (weight === undefined) {
      throw new Error(`${t.path.join('.')}: unsupported weight ${t.$value}`);
    }
    return `public static let ${camel(t.path.slice(1))}: Font.Weight = .${weight}`;
  });
  const numbers = (root, sub) =>
    under(root)
      .filter((t) => (sub === undefined ? true : t.path[1] === sub))
      .map(
        (t) =>
          `public static let ${camel(t.path.slice(sub === undefined ? 1 : 2))}: CGFloat = ${t.$value}`,
      );
  const metrics = [
    `public static let borderWidth: CGFloat = ${points(need(tokens, 'border-width'))}`,
    `public static let focusOutlineWidth: CGFloat = ${points(need(tokens, 'focus.outline-width'))}`,
    `public static let focusOutlineOffset: CGFloat = ${points(need(tokens, 'focus.outline-offset'))}`,
  ];

  const scheme = tokens.find((t) => t.path[0] === 'color-scheme');
  if (scheme === undefined || !schemes.has(scheme.$value)) {
    throw new Error(`${file.destination}: color-scheme must be light or dark`);
  }

  return `// Generated by Style Dictionary from tokens/*.json. Do not edit.

import CoreGraphics
import SwiftUI

extension Color {
${colorLines.join('\n\n')}
}

public enum Palette {
    public static let all: [String: Color] = [
${palette}
    ]
}
${block('FontFamily', families)}${block('FontWeights', fontWeights)}${block('Radius', numbers('radius'))}${block('TextSize', numbers('native', 'size'))}${block('Spacing', numbers('native', 'space'))}${block('WindowWidth', numbers('native', 'width'))}${block('Metric', metrics)}
public enum Scheme {
    public static let colorScheme: ColorScheme = .${scheme.$value}
}
`;
};
