const nest = (tokens) => {
  const tree = {};
  for (const token of tokens) {
    const path =
      token.path[0] === 'color-scheme' ? ['colorScheme'] : token.path;
    let node = tree;
    for (const key of path.slice(0, -1)) node = node[key] ??= {};
    node[path.at(-1)] = token.$value;
  }
  return tree;
};

export const tsFormat = ({ dictionary, file }) => {
  if (dictionary.allTokens.length === 0) {
    throw new Error(`${file.destination}: the token set is empty`);
  }
  const tree = nest(dictionary.allTokens.filter((t) => t.path[0] !== 'native'));
  const groups = Object.entries(tree)
    .map(
      ([group, value]) =>
        `export const ${camel(group)} = ${JSON.stringify(value, null, 2)} as const;\n`,
    )
    .join('\n');
  const names = Object.keys(tree).map(camel).join(', ');
  return `// Generated by Style Dictionary from tokens/*.json. Do not edit.\n\n${groups}\nexport const tokens = { ${names} } as const;\n`;
};

const camel = (name) => name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
